export const FULL_INGRIDIENTS = 'FULL_INGRIDIENTS';

export const SET_SELECTED_INGRIDIENTS = 'SET_SELECTED_INGRIDIENTS';
export const ADD_SELECTED_INGRIDIENT = 'ADD_SELECTED_INGRIDIENT';
export const SET_SELECTED_BUN = 'SET_SELECTED_BUN';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const REMOVE_SELECTED_ITEM = 'REMOVE_SELECTED_ITEM';

export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';
export const SET_MODAL_VIEW_STATE = 'SET_MODAL_VIEW_STATE';
export const INGRIDIENT_MODAL_TYPE = 'INGRIDIENT_MODAL_TYPE';
export const ORDER_MODAL_TYPE = 'ORDER_MODAL_TYPE';