export const FULL_INGREDIENTS = "FULL_INGREDIENTS";

export const SET_SELECTED_INGREDIENTS = "SET_SELECTED_INGREDIENTS";
export const ADD_SELECTED_INGREDIENT = "ADD_SELECTED_INGREDIENT";
export const INSERT_SELECTED_INGREDIENT = "INSERT_SELECTED_INGREDIENT";
export const SET_SELECTED_BUN = "SET_SELECTED_BUN";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
export const REMOVE_SELECTED_ITEM = "REMOVE_SELECTED_ITEM";
export const SET_INSERT_POSITION = "SET_INSERT_POSITION";
export const UPDATE_POSITION = "UPDATE_POSITION";
export const CLEAR_SELECTION = "CLEAR_SELECTION";

export const SET_MODAL_CONTENT = "SET_MODAL_CONTENT";
export const SET_MODAL_VIEW_STATE = "SET_MODAL_VIEW_STATE";
export const INGREDIENT_MODAL_TYPE = "INGREDIENT_MODAL_TYPE";
export const ORDER_MODAL_TYPE = "ORDER_MODAL_TYPE";

export const SET_DRAG_STYLE_TYPE = "SET_DRAG_STYLE_TYPE";
